### ISSUE TITLE
next.js Showcase

### ISSUE THREAD

**Issue by mfranzke** [db-ui/elements#78]

**Comment by nmerget** [comment]
I tried this...

Solution 1, Use the react-output-target and react components directly:

  - The problem here was, that the stencil `componentWillLoad` function will cause an issue (https://nextjs.org/docs/messages/react-hydration-error).
  - I tried to exclude `componentWillLoad` and tried to add an `useEffect` inside the next.js app, but this didn't work like i tought.
  - The components rendered fine, but because of the react-hydration-error we just show a "normal" React app. So we wouldn't use SSR here, which makes next.js unnecessary.

Solution 2, Stencil way of SSR (https://stenciljs.com/docs/static-site-generation-server-side-rendering-ssr):

- I tried to look at this example (https://github.com/jagreehal/nextjs-stenciljs-ssr-example).
- But our compontents didn't render correctly...
- Moreover it is only working with another server like express, which seams unsexy for me.


=> I think we shouldn't focus on this topic. If people want to use SSR, they should use https://github.com/db-ui/core and create their own components.
